name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: 
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
          distribution: adopt
          cache: gradle

      - name: Build with Gradlew
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew shadowJar
          mkdir artifacts
          cp build/libs/* artifacts/
          cp bukkit/build/libs/* artifacts/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: artifacts

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: github.event_name == 'release'
        env:
          GHR_PATH: artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
